### ISSUE TITLE
V0.1

### ISSUE THREAD

**Issue by DarkestSpawn** [BigfootACA/device_nubia_nx729j#1]
Booted fine, Just extremely slow response times.

**Comment by JWnSC** [comment]
Same here, it seems to work. I'm using stock decrypted rom, modified fstab and repacked super.img and flashed with fastboot. It reads internal storage fine. A little lag when using also defaults to Chinese language even after changing in twrp

If you need a tester let me know.. Nice work 👍

**Comment by BigfootACA** [comment]
this problem was caused by haptics, it has been fixed now
d1f9859bd859cc75de021c5dd44faf2db820fb3b
